railscast-ng is gone... :(

diff --git a/scripts/atom b/scripts/atom
--- a/scripts/atom
+++ b/scripts/atom
@@ -1,20 +1,35 @@
 #!/bin/bash
 sudo bash -c ":" || exit 1
 
+function install {
+	if ! pacman -Qi $i > /dev/null; then
+		sudo pacman --noconfirm -S $1
+	fi
+}
 function apmget {
-    package=$1
-    echo $package
-    if [[ ! -d "$HOME/.atom/packages/$package" ]]; then
-        apm install $package
-    fi
+	package=$1
+	echo $package
+	if [[ ! -d "$HOME/.atom/packages/$package" ]]; then
+		apm install $package
+	fi
 }
 
 if ! which atom >> /dev/null; then
-    echo "Please install atom first"
+	read -p "Please install atom first:  (y/N)?" DO
+	if [ "$DO" = "y" ]; then
+		install atom
+		echo
+		echo
+		echo "Please launch atom once before continuing... (enter)"
+		read;
+	else
+		exit 1
+	fi
 fi
 
 if ! which apm >> /dev/null; then
-    echo "Atom package manager not found!"
+	echo "Atom package manager not found!"
+	exit 1
 fi
 
 
@@ -24,7 +39,8 @@ fi
 
 apm disable language-python
 apmget MagicPython
-apmget railscast-theme-ng
+#apmget railscast-theme-ng # 404...
+apmget railscast-theme
 apmget selection-highlight
 apmget markdown-preview
 apmget atom-beautify
